#App Properties
spring.application.name=capstone-mimi-shop
#Server Properties
spring.datasource.url=jdbc:mysql://localhost:3306/DATN_SD_70?useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
#ThymeLeaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
#Cloudinary
cloudinary.cloud-name=dwsu2j5pf
cloudinary.api-key=292794547552419
cloudinary.api-secret=epTqE1poH0xxWJd0FN0v-fXIKs0
#Resource location
spring.web.resources.static-locations=classpath:/static/,classpath:/assets/
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=capstoneshops@gmail.com
spring.mail.password=epfn lkcc hmfe exxj
spring.mail.properties.mail.transport.protocol=TLSv1.2
spring.mail.properties.mail.smtp.port=25
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
